version: '3.1'
services:
  postgresql:
    image: postgres:12
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      POSTGRES_DATABASE: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: aaabbbccc181818ddd





